/**
 * HelpPanel - In-app user guide with quickstart and deep-dive sections.
 */

import { useState } from 'react';
import { X, ChevronRight, Rocket, Lightbulb, FileText, LayoutList, Bug, BarChart3, BookOpen, Shield, Bot } from 'lucide-react';
import { MarkdownContent } from '@/components/shared/MarkdownContent';
import logoLight from '@/assets/logo-light.jpg';
import logoDark from '@/assets/logo-dark.jpg';

interface HelpPanelProps {
  onClose: () => void;
}


interface Section {
  id: string;
  title: string;
  icon: React.ReactNode;
  content: string;
}

function getSections(): Section[] {
  const sections: Section[] = [
    {
      id: 'quickstart',
      title: 'Quickstart',
      icon: <Rocket size={16} />,
      content: `
## Welcome to Okto Pulse

Okto Pulse is a **spec-driven project management tool** designed for AI-assisted software development. It guides you from raw ideas to shipped code through a structured pipeline:

**Ideation** → **Refinement** → **Spec** → **Tasks**

### Get started

#### Step 1 — Initialize (first time only)

If you haven't already, run in your terminal:

\`\`\`bash
okto-pulse init
\`\`\`

This creates:
- A default **board** ("My Board")
- A default **agent** ("Local Agent") with an API key
- A **\`.mcp.json\`** file in the current directory with the MCP connection config

The output will show something like:

\`\`\`
Board created: My Board
Agent created: Local Agent
API Key: dash_a1b2c3d4...
MCP URL: http://localhost:8101/mcp?api_key=dash_a1b2c3d4...

.mcp.json generated at: /your/project/.mcp.json
\`\`\`

#### Step 2 — Start the server

\`\`\`bash
okto-pulse serve
\`\`\`

This starts the **API + Frontend** (port 8100) and the **MCP server** (port 8101). Open \`http://localhost:8100\` in your browser.

#### Step 3 — Connect your AI tool via MCP

The \`.mcp.json\` generated by \`okto-pulse init\` is ready to use. Most AI tools auto-detect it:

- **Claude Code / Claude Desktop** — reads \`.mcp.json\` from your project root automatically
- **Cursor** — add to your MCP settings in Cursor preferences
- **VS Code (Copilot)** — add to \`.vscode/mcp.json\`
- **Windsurf / Cline** — reads \`.mcp.json\` from project root

**The \`.mcp.json\` format:**

\`\`\`json
{
  "mcpServers": {
    "okto-pulse": {
      "url": "http://localhost:8101/mcp?api_key=dash_your_key_here"
    }
  }
}
\`\`\`

> **Important:** The MCP server must be running (\`okto-pulse serve\`) for AI tools to connect. The agent must have access to the board — the default setup handles this automatically.

#### Step 4 — Create your first ideation

Go to the **Ideations** tab and describe your idea. The AI agent can now help you evaluate, refine, and spec it out through the 119+ MCP tools available.

#### Step 5 — Let the pipeline guide you

Evaluate the ideation → refine if needed → write a spec with acceptance criteria and test scenarios → break it into task cards on the Kanban board.

### Managing agents

To create additional agents or manage board access, open **Menu** (☰) → **Agents**:
- **My Agents** tab — create, view API keys, regenerate keys, delete agents
- **Board Access** tab — grant or revoke agent access to the current board

### Custom ports

\`\`\`bash
okto-pulse --api-port 9000 --mcp-port 9001 serve
\`\`\`

Remember to update the MCP URL in your \`.mcp.json\` if you change the MCP port.

### The pipeline at a glance

| Stage | Purpose | Key actions |
|-------|---------|-------------|
| **Ideation** | Capture the idea | Write, ask questions, evaluate complexity |
| **Refinement** | Deepen analysis (medium/large ideas) | Break down scope, add knowledge, make decisions |
| **Spec** | Define what to build | Acceptance criteria, test scenarios, business rules, API contracts |
| **Tasks** | Build it | Kanban cards, dependencies, conclusions, bug tracking |

> **Tip:** Each stage has a Q&A system — use it to clarify doubts and document decisions before moving forward.
`,
    },
    {
      id: 'agents',
      title: 'Agents & MCP',
      icon: <Bot size={16} />,
      content: `
## Agents & MCP — Connect AI tools to your board

Agents are the bridge between AI tools (Claude Code, Cursor, Windsurf, etc.) and your Okto Pulse boards. The Community edition comes with a **default agent pre-configured**.

### How it works

\`\`\`
Your AI Tool (Claude Code, Cursor, etc.)
    ↓ MCP protocol
Okto Pulse MCP Server (default port 8101)
    ↓ API key authentication
Agent identity resolved → board access checked
    ↓
119+ tools available (create cards, move specs, add comments, etc.)
\`\`\`

### Default setup (automatic)

When you run \`okto-pulse init\`, the system creates:
- A **"Local Agent"** with an API key
- A **"My Board"** with the agent already granted access
- A **\`.mcp.json\`** file in the current directory

This means **your AI tool is ready to connect immediately** — no manual setup required.

### Connecting your AI tool

Most tools auto-detect the \`.mcp.json\` file:

| Tool | How to connect |
|------|---------------|
| **Claude Code** | Auto-detects \`.mcp.json\` in project root — just start Claude Code |
| **Claude Desktop** | Copy the config to Claude Desktop settings → MCP servers |
| **Cursor** | Add the MCP URL to Cursor preferences → MCP settings |
| **VS Code** | Copy to \`.vscode/mcp.json\` |
| **Windsurf / Cline** | Auto-detects \`.mcp.json\` in project root |

**The \`.mcp.json\` file looks like this:**

\`\`\`json
{
  "mcpServers": {
    "okto-pulse": {
      "url": "http://localhost:8101/mcp?api_key=dash_your_key_here"
    }
  }
}
\`\`\`

### Creating additional agents

You can create more agents beyond the default one:

1. Open **Menu** (☰) → **Agents**
2. In the **"My Agents"** tab, enter a name and click **Create**
3. **Copy the API key immediately** — it's only shown once
4. Switch to **"Board Access"** tab and grant the new agent access to your board

### Managing board access

In **Menu** (☰) → **Agents** → **"Board Access"** tab:
- See which agents have access to the current board
- **Grant Access** — select an agent from the dropdown
- **Revoke** — remove an agent's access

### API key management

- **View key** — In the Agents panel, your key is visible (copy it)
- **Regenerate key** — If compromised, click **Regenerate**. The old key stops working immediately.
- **Lost key** — Keys are hashed in the database. If lost, regenerate a new one.

### Running on custom ports

If you changed the MCP port:

\`\`\`bash
okto-pulse --mcp-port 9001 init
okto-pulse --mcp-port 9001 serve
\`\`\`

The \`.mcp.json\` is regenerated with the new port on \`init\`. Make sure your AI tool points to the correct URL.

### Troubleshooting

- **"Connection refused"** — Make sure \`okto-pulse serve\` is running
- **"Unauthorized"** — Check the API key in \`.mcp.json\` matches the one from \`init\` output
- **"No board access"** — Grant the agent access in Menu → Agents → Board Access
- **Tools not appearing** — Restart your AI tool after adding the MCP config
`,
    },
    {
      id: 'ideations',
      title: 'Ideations',
      icon: <Lightbulb size={16} />,
      content: `
## Ideations — Capture ideas before building

An ideation is the starting point. It answers: *"What do we want to do and why?"*

### Creating an ideation

Click **"+ New Ideation"** in the Ideations tab and fill in:
- **Title** — Short description of the idea
- **Description** — Full explanation of the problem and proposed solution
- **Context** — Background info, user needs, market context

### Ideation lifecycle

\`draft\` → \`evaluating\` → \`refined\` → \`done\`

- **Draft** — Initial state; write and iterate freely
- **Evaluating** — Being assessed for complexity and feasibility
- **Refined** — Evaluation complete; complexity assigned (small / medium / large)
- **Done** — Ready to become a Spec (small) or Refinement (medium/large)

### Complexity and what comes next

| Complexity | Next step |
|-----------|-----------|
| **Small** | Skip refinement → create a Spec directly |
| **Medium / Large** | Create a Refinement first to break down the scope |

### Q&A

Use the Q&A section to ask and answer questions about the ideation. This creates a documented decision trail that stays with the idea. You can also create **choice questions** where multiple options are presented and voted on.

### Snapshots

When an ideation moves to "done", an immutable snapshot is captured. This preserves the exact state for future reference — the ideation itself becomes read-only.
`,
    },
    {
      id: 'refinements',
      title: 'Refinements',
      icon: <FileText size={16} />,
      content: `
## Refinements — Deepen medium/large ideas

A refinement takes a "done" ideation and breaks it into detailed analysis: scope decisions, knowledge bases, and architecture considerations.

### When to use refinements

- The ideation was evaluated as **medium** or **large** complexity
- The scope is too broad for a single spec
- You need to make architectural decisions before specifying

### Creating a refinement

From a "done" ideation, click **"Derive Spec/Refinement"**. Choose Refinement for medium/large ideas.

### Refinement lifecycle

\`draft\` → \`in_progress\` → \`approved\` → \`done\`

### Key features

- **Scope** — Define what's in scope and out of scope
- **Decisions** — Document key technical or product decisions with rationale
- **Knowledge Base** — Attach reference documents, technical notes, or research
- **Q&A** — Same question system as ideations, with choice questions
- **Analysis** — Deep-dive into the problem space

### From refinement to spec

When a refinement is "done", you can derive one or more Specs from it. Each spec inherits context from the refinement.
`,
    },
    {
      id: 'specs',
      title: 'Specs',
      icon: <FileText size={16} />,
      content: `
## Specs — Define exactly what to build

A spec is the **blueprint for implementation**. It contains everything needed to write code: acceptance criteria, test scenarios, business rules, API contracts, and functional requirements.

### Creating a spec

Specs are derived from "done" ideations (small) or "done" refinements (medium/large). Click **"Derive Spec"** from the source entity.

### Spec lifecycle

\`draft\` → \`review\` → \`approved\` → \`in_progress\` → \`done\`

### Governance rules (enforced by the system)

Before a spec can move to **"done"**, it must meet these criteria:

1. **Full test coverage** — Every acceptance criterion must have at least one test scenario linked to it (unless \`skip_test_coverage\` is enabled)
2. **All tasks complete** — Every linked task card (non-bug) must be in \`done\` or \`cancelled\` status

### Spec sections

| Section | Purpose |
|---------|---------|
| **Acceptance Criteria** | What "done" looks like — measurable conditions |
| **Functional Requirements** | Detailed behavior descriptions |
| **Test Scenarios** | How to verify each criterion |
| **Business Rules** | Domain logic that must be enforced |
| **API Contracts** | Endpoint definitions (method, path, request/response) |
| **Knowledge Base** | Reference docs and technical notes |
| **Skills** | Reusable spec skills that can be loaded |
| **Q&A** | Questions and documented decisions |

### Coverage governance

The system enforces traceability:
- **Test scenarios** must cover all acceptance criteria
- **Business rules** must cover all functional requirements (if enabled)
- **Technical requirements** must link to task cards (if enabled)

These checks can be bypassed per-spec (\`skip_test_coverage\`) or globally in board Settings.
`,
    },
    {
      id: 'tasks',
      title: 'Tasks (Kanban)',
      icon: <LayoutList size={16} />,
      content: `
## Tasks — The Kanban board

Tasks are the work items that implement a spec. They live on a Kanban board with drag-and-drop columns.

### Creating tasks

Tasks can only be created when linked to a **"done" spec**. This ensures every task has a clear definition of what to build and how to test it.

### Task lifecycle (columns)

\`not_started\` → \`started\` → \`in_progress\` → \`done\`

Additional statuses: \`on_hold\`, \`cancelled\`

### Governance rules

Before a task can be **started**:
1. All test scenarios in the spec must have linked task cards
2. All functional requirements must have linked business rules (if enabled)
3. All technical requirements must link to tasks (if enabled)

Before a task moves to **done**:
- A **conclusion** is required — describe what was done and why

### Dependencies

Tasks can have dependencies on other tasks:
- Add a dependency via the task detail panel
- A task **cannot be moved forward** if its dependencies are not yet done
- Dependencies are shown visually on the board

### Priority levels

\`critical\` > \`very_high\` > \`high\` > \`medium\` > \`low\` > \`none\`

### Labels

Free-form tags to categorize tasks (e.g., "frontend", "database", "auth").

### Archiving

Done or cancelled tasks can be archived to keep the board clean. Archived tasks can be restored at any time. Use the **"Show archived"** toggle to view them.
`,
    },
    {
      id: 'bugs',
      title: 'Bug tracking',
      icon: <Bug size={16} />,
      content: `
## Bug cards — Track and fix defects

Bug cards are a special type of task card (\`card_type=bug\`) for defects discovered during or after implementation.

### When to create bugs

- A completed task doesn't work as expected
- A test scenario fails after code changes
- You discover a regression in existing functionality

> **Important:** Always register bugs — never fix them silently. Untracked bugs mean unmeasured quality.

### Creating a bug card

Bug cards require:

| Field | Required | Description |
|-------|----------|-------------|
| \`card_type\` | Yes | Must be \`"bug"\` |
| \`origin_task_id\` | Yes | The task where the bug was found |
| \`severity\` | Yes | \`critical\`, \`major\`, or \`minor\` |
| \`expected_behavior\` | Yes | What should happen |
| \`observed_behavior\` | Yes | What actually happens |
| \`steps_to_reproduce\` | No | How to reproduce |
| \`action_plan\` | No | Proposed fix approach |

The \`spec_id\` is auto-resolved from the origin task.

### Bug workflow (test-first)

The system enforces a **test-first** approach for bugs:

1. **Create** the bug card (status: \`not_started\`)
2. **Create a new test scenario** that covers the bug's failure case
3. **Create a test task** and link it to the bug
4. **Move to \`in_progress\`** — blocked until test task is linked
5. **Fix** the bug
6. **Move to \`done\`** with a conclusion

### Severity levels

| Level | Meaning |
|-------|---------|
| **Critical** | System down, data loss, security vulnerability |
| **Major** | Core feature broken, significant UX impact |
| **Minor** | Cosmetic, edge case, workaround exists |
`,
    },
    {
      id: 'analytics',
      title: 'Analytics',
      icon: <BarChart3 size={16} />,
      content: `
## Analytics — Track progress and quality

The Analytics dashboard (accessible from the menu) provides metrics across your boards.

### Available metrics

- **Pipeline funnel** — Ideations → Refinements → Specs → Tasks → Done
- **Specs done** — Completion rate over time
- **Bug rate** — Bugs per spec and per task
- **Bug severity distribution** — Critical / Major / Minor breakdown
- **Test coverage** — Acceptance criteria with linked test scenarios
- **Rules coverage** — Functional requirements with linked business rules
- **Triage time** — How quickly bugs get their first test task linked

### Export

Analytics data can be exported as CSV for external reporting.
`,
    },
    {
      id: 'guidelines',
      title: 'Guidelines',
      icon: <BookOpen size={16} />,
      content: `
## Guidelines — Shared knowledge and standards

Guidelines are reusable documents that define standards, patterns, and conventions for your project.

### Types

- **Board guidelines** — Specific to a single board
- **Global guidelines** — Available across all boards, can be linked to any board

### Creating guidelines

Open **Guidelines** from the menu. You'll see two tabs:
1. **Board Guidelines** — Create inline or link from the global catalog
2. **Global Catalog** — Create, edit, and manage global guidelines

Guidelines support **Markdown** with Mermaid diagrams, tags, and version tracking (global only).

### Use cases

- Coding standards and conventions
- Architecture patterns
- Review checklists
- Onboarding documentation
- Decision records
`,
    },
    {
      id: 'governance',
      title: 'Governance & rules',
      icon: <Shield size={16} />,
      content: `
## Governance — Quality gates enforced by the system

Okto Pulse enforces a set of governance rules to maintain quality and traceability throughout the pipeline.

### Spec → Done gates

| Rule | What it checks |
|------|---------------|
| **Test coverage** | Every acceptance criterion has at least one test scenario |
| **Tasks complete** | All linked tasks (non-bug) are done or cancelled |

### Task → Started gates

| Rule | What it checks |
|------|---------------|
| **Test scenario coverage** | Every test scenario has at least one linked task card |
| **Business rules coverage** | Every functional requirement has at least one linked business rule |
| **TR coverage** | Every technical requirement links to a task card |

### Task → Done gates

| Rule | What it checks |
|------|---------------|
| **Conclusion required** | A conclusion describing the work must be provided |

### Bug → In Progress gates

| Rule | What it checks |
|------|---------------|
| **Test task linked** | At least one new test task must be linked to the bug |
| **New scenario required** | The test scenario must have been created *after* the bug card |

### Overrides

All coverage checks can be bypassed:
- **Per spec** — Toggle \`skip_test_coverage\`, \`skip_rules_coverage\`, or \`skip_trs_coverage\` on the spec
- **Per board** — Toggle global overrides in **Settings** (menu → Settings)

### Dependencies

- A task cannot move forward if its dependencies are not done
- Dependencies create a directed acyclic graph (circular dependencies are rejected)
`,
    },
  ];

  return sections;
}

export function HelpPanel({ onClose }: HelpPanelProps) {
  const sections = getSections();
  const [activeSection, setActiveSection] = useState('quickstart');

  const current = sections.find(s => s.id === activeSection) || sections[0];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40" onClick={onClose}>
      <div
        className="relative w-[90vw] max-w-5xl bg-white dark:bg-gray-900 rounded-xl shadow-2xl border border-gray-200 dark:border-gray-700 flex overflow-hidden"
        style={{ height: '85vh' }}
        onClick={e => e.stopPropagation()}
      >
        {/* Sidebar navigation */}
        <nav className="w-56 shrink-0 border-r border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50 flex flex-col">
          <div className="px-4 py-4 border-b border-gray-200 dark:border-gray-700 flex items-center gap-2.5">
            <img src={logoLight} alt="Okto Pulse" className="h-8 w-8 rounded dark:hidden" />
            <img src={logoDark} alt="Okto Pulse" className="h-8 w-8 rounded hidden dark:block" />
            <div>
              <h2 className="text-sm font-bold text-gray-800 dark:text-gray-200">
                Help Guide
              </h2>
              <p className="text-[10px] text-gray-400 mt-0.5">
                Community Edition
              </p>
            </div>
          </div>
          <div className="flex-1 overflow-y-auto py-2">
            {sections.map(section => (
              <button
                key={section.id}
                onClick={() => setActiveSection(section.id)}
                className={`w-full text-left px-4 py-2 text-sm flex items-center gap-2.5 transition-colors ${
                  activeSection === section.id
                    ? 'bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 font-medium border-r-2 border-blue-500'
                    : 'text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700/50'
                }`}
              >
                <span className="shrink-0 opacity-70">{section.icon}</span>
                {section.title}
                {activeSection === section.id && <ChevronRight size={12} className="ml-auto opacity-50" />}
              </button>
            ))}
          </div>
        </nav>

        {/* Content area */}
        <div className="flex-1 flex flex-col min-w-0">
          <div className="flex items-center justify-between px-6 py-3 border-b border-gray-200 dark:border-gray-700">
            <h3 className="text-sm font-semibold text-gray-800 dark:text-gray-200 flex items-center gap-2">
              {current.icon}
              {current.title}
            </h3>
            <button
              onClick={onClose}
              className="p-1.5 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
            >
              <X size={18} />
            </button>
          </div>
          <div className="flex-1 overflow-y-auto px-6 py-4">
            <MarkdownContent content={current.content} />
          </div>
        </div>
      </div>
    </div>
  );
}
